#!/bin/bash
#
# Copyright (C) 2008  June Tate-Gans, All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

dotbash-project-pre-hook()
{
    pushd ~/.bash.d >/dev/null
}

dotbash-project-post-hook()
{
    while expr $(dirs -v |wc -l) - 1 > /dev/null; do
        popd >/dev/null
    done
}

dotbash-project-init-hook()
{
    export EDITOR="vim"
    export LESS="-MR"

    project-set-prompt 'dotbash'
}

add-hook _PROJECT_PRE_HOOKS dotbash-project-pre-hook
add-hook _PROJECT_POST_HOOKS dotbash-project-post-hook
add-hook _INIT_POST_HOOKS dotbash-project-init-hook
